name: build

on:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Establish build date-time stamp
        shell: bash
        run: |
          set -x
          export DT=$(date +%F_%H%M%S)
          export ZIPFILE=pltu-macos-$DT.zip
          echo "ZIPFILE=$ZIPFILE" >> $GITHUB_ENV
      - name: Build and validate plugins
        shell: bash
        run: |
          set -x
          cd plugins/Plateau
          make
          cd ../..
          curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_macOS.zip" -o pluginval.zip
          unzip pluginval.zip
          pluginval.app/Contents/MacOS/pluginval --strictness-level 5 --verbose --validate-in-process --output-dir . bin/Plateau.vst3
          mkdir -p ~/Library/Audio/Plug-Ins/Components
          cp -R bin/Plateau.component ~/Library/Audio/Plug-Ins/Components
          # https://github.com/Tracktion/pluginval/issues/122
          killall -9 AudioComponentRegistrar || true
          pluginval.app/Contents/MacOS/pluginval --strictness-level 5 --verbose --validate-in-process --output-dir . bin/Plateau.component
          echo "Creating $ZIPFILE ..."
          cd bin && zip "$ZIPFILE" -r Plateau.* && mv "$ZIPFILE" ~
      - uses: actions/upload-artifact@v4
        with:
          name: "${{ env.ZIPFILE }}"
          path: "~/${{ env.ZIPFILE }}"
